### PR TITLE
fix copy/paste typo

### PR DESCRIPTION
**Pull request by tolry**

### CODE REVIEW

**Comment by seveas** [comment]
Heh, thanks :) I'll add a test to make sure such silly issues won't appear again.

**Comment by tolry** [comment]
sorry, my bad - should have written the test first, then fixed the typo, then submitted both as PR - of course :wink:

**Comment by tolry** [comment]
Still on my "open PRs" list - any reason not to merge this?

**Comment by seveas** [comment]
Just lack of time.

**Comment by seveas** [comment]
Thanks, applied as 5de669d

**Pull request closed without merging**
